<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
/*
|---------------------------------------------------------------
| UPDATE VERSIONS
|---------------------------------------------------------------
|
| File: assets/update/versions.php
| System Version: 1.0.3
|
| File containing all the versions the system can updated from
|
| DO NOT EDIT THIS FILE. DOING SO WILL BREAK THE NOVA UPDATE SYSTEM
|
*/

$version_array = array(
	'100', '101', '102'
);

/* End of file versions.php */
/* Location: ./application/assets/update/versions.php */