<?php

namespace Fuel\Migrations;

class Create_form_fields
{
	public function up()
	{
		\DBUtil::create_table('form_fields', array(
			'id' => array('type' => 'INT', 'constraint' => 11, 'auto_increment' => true),
			'form_key' => array('type' => 'VARCHAR', 'constraint' => 20),
			'section_id' => array('type' => 'INT', 'constraint' => 11, 'null' => true),
			'type' => array('type' => 'VARCHAR', 'constraint' => 50, 'default' => 'text'),
			'label' => array('type' => 'VARCHAR', 'constraint' => 255, 'null' => true),
			'order' => array('type' => 'INT', 'constraint' => 5, 'null' => true),
			'display' => array('type' => 'TINYINT', 'constraint' => 1, 'default' => 1),
			'restriction' => array('type' => 'INT', 'constraint' => 11, 'null' => true),
			'help' => array('type' => 'TEXT', 'null' => true),
			'selected' => array('type' => 'VARCHAR', 'constraint' => 50, 'null' => true),
			'value' => array('type' => 'VARCHAR', 'constraint' => 255, 'null' => true),
			'html_name' => array('type' => 'VARCHAR', 'constraint' => 100, 'null' => true),
			'html_id' => array('type' => 'VARCHAR', 'constraint' => 100, 'null' => true),
			'html_class' => array('type' => 'VARCHAR', 'constraint' => 255, 'default' => 'span4'),
			'html_rows' => array('type' => 'INT', 'constraint' => 3, 'default' => 5),
			'placeholder' => array('type' => 'TEXT', 'null' => true),
			'updated_at' => array('type' => 'BIGINT', 'constraint' => 20, 'null' => true),
		), array('id'));

		$data = array(
			array(
				'form_key' => 'character',
				'section_id' => 1,
				'type' => 'select',
				'html_name' => 'gender',
				'html_id' => 'gender',
				'html_rows' => 0,
				'label' => 'Gender',
				'order' => 1),
			array(
				'form_key' => 'character',
				'section_id' => 1,
				'type' => 'text',
				'html_name' => 'species',
				'html_id' => 'species',
				'html_rows' => 0,
				'label' => 'Species',
				'placeholder' => 'e.g. Human',
				'order' => 2),
			array(
				'form_key' => 'character',
				'section_id' => 1,
				'type' => 'text',
				'html_name' => 'age',
				'html_id' => 'age',
				'html_rows' => 0,
				'html_class' => 'span1',
				'label' => 'Age',
				'placeholder' => 'Age',
				'order' => 3),
			array(
				'form_key' => 'character',
				'section_id' => 2,
				'type' => 'text',
				'html_name' => 'height',
				'html_id' => 'height',
				'html_rows' => 0,
				'label' => 'Height',
				'placeholder' => 'e.g. 6\'2"',
				'order' => 1),
			array(
				'form_key' => 'character',
				'section_id' => 2,
				'type' => 'text',
				'html_name' => 'weight',
				'html_id' => 'weight',
				'html_rows' => 0,
				'label' => 'Weight',
				'placeholder' => 'e.g. 215 lbs.',
				'order' => 2),
			array(
				'form_key' => 'character',
				'section_id' => 2,
				'type' => 'text',
				'html_name' => 'hair_color',
				'html_id' => 'hair_color',
				'html_rows' => 0,
				'label' => 'Hair Color',
				'placeholder' => 'Hair Color',
				'order' => 3),
			array(
				'form_key' => 'character',
				'section_id' => 2,
				'type' => 'text',
				'html_name' => 'eye_color',
				'html_id' => 'eye_color',
				'html_rows' => 0,
				'label' => 'Eye Color',
				'placeholder' => 'Eye Color',
				'order' => 4),
			array(
				'form_key' => 'character',
				'section_id' => 2,
				'type' => 'textarea',
				'html_name' => 'physical_desc',
				'html_id' => 'physical_desc',
				'html_rows' => 3,
				'html_class' => 'span8',
				'label' => 'Physical Description',
				'placeholder' => 'Enter your physical description here',
				'order' => 5),
			array(
				'form_key' => 'character',
				'section_id' => 3,
				'type' => 'text',
				'html_name' => 'spouse',
				'html_id' => 'spouse',
				'html_rows' => 0,
				'label' => 'Spouse',
				'placeholder' => 'Spouse',
				'order' => 1),
			array(
				'form_key' => 'character',
				'section_id' => 3,
				'type' => 'textarea',
				'html_name' => 'children',
				'html_id' => 'children',
				'html_rows' => 3,
				'label' => 'Children',
				'placeholder' => 'Enter your character\'s children here',
				'order' => 2),
			array(
				'form_key' => 'character',
				'section_id' => 3,
				'type' => 'text',
				'html_name' => 'father',
				'html_id' => 'father',
				'html_rows' => 0,
				'label' => 'Father',
				'placeholder' => 'Father',
				'order' => 3),
			array(
				'form_key' => 'character',
				'section_id' => 3,
				'type' => 'text',
				'html_name' => 'mother',
				'html_id' => 'mother',
				'html_rows' => 0,
				'label' => 'Mother',
				'placeholder' => 'Mother',
				'order' => 4),
			array(
				'form_key' => 'character',
				'section_id' => 3,
				'type' => 'textarea',
				'html_name' => 'siblings',
				'html_id' => 'siblings',
				'html_rows' => 3,
				'label' => 'Siblings',
				'placeholder' => 'Enter your character\'s siblings here',
				'order' => 5),
			array(
				'form_key' => 'character',
				'section_id' => 3,
				'type' => 'textarea',
				'html_name' => 'other_family',
				'html_id' => 'other_family',
				'html_rows' => 3,
				'label' => 'Other Family',
				'placeholder' => 'Enter your character\'s other family here',
				'order' => 6),
			array(
				'form_key' => 'character',
				'section_id' => 4,
				'type' => 'textarea',
				'html_name' => 'personality',
				'html_id' => 'personality',
				'html_rows' => 5,
				'html_class' => 'span8',
				'label' => 'General Overview',
				'placeholder' => 'Enter your character\'s general personality overview here',
				'order' => 1),
			array(
				'form_key' => 'character',
				'section_id' => 4,
				'type' => 'textarea',
				'html_name' => 'strengths',
				'html_id' => 'strengths',
				'html_rows' => 5,
				'html_class' => 'span8',
				'label' => 'Strengths &amp; Weaknesses',
				'placeholder' => 'Enter your character\'s strengths and weaknesses here',
				'order' => 2),
			array(
				'form_key' => 'character',
				'section_id' => 4,
				'type' => 'textarea',
				'html_name' => 'ambitions',
				'html_id' => 'ambitions',
				'html_rows' => 5,
				'html_class' => 'span8',
				'label' => 'Ambitions',
				'placeholder' => 'Enter your character\'s ambitions here',
				'order' => 3),
			array(
				'form_key' => 'character',
				'section_id' => 4,
				'type' => 'textarea',
				'html_name' => 'hobbies',
				'html_id' => 'hobbies',
				'html_rows' => 5,
				'html_class' => 'span8',
				'label' => 'Hobbies &amp; Interests',
				'placeholder' => 'Enter your character\'s hobbies and interests here',
				'order' => 4),
			array(
				'form_key' => 'character',
				'section_id' => 4,
				'type' => 'textarea',
				'html_name' => 'languages',
				'html_id' => 'languages',
				'html_rows' => 2,
				'html_class' => 'span8',
				'label' => 'Languages',
				'placeholder' => 'Enter your character\'s known languages here',
				'order' => 5),
			array(
				'form_key' => 'character',
				'section_id' => 5,
				'type' => 'textarea',
				'html_name' => 'history',
				'html_id' => 'history',
				'html_rows' => 15,
				'html_class' => 'span8',
				'label' => 'History',
				'placeholder' => 'Enter your character\'s personal history here',
				'order' => 1),
			array(
				'form_key' => 'character',
				'section_id' => 5,
				'type' => 'textarea',
				'html_name' => 'service_record',
				'html_id' => 'service_record',
				'html_rows' => 15,
				'html_class' => 'span8',
				'label' => 'Service Record',
				'placeholder' => 'Enter your character\'s service record here',
				'order' => 2),
			array(
				'form_key' => 'specs',
				'section_id' => 7,
				'type' => 'text',
				'html_name' => 'class',
				'html_id' => 'class',
				'html_rows' => 0,
				'label' => 'Class',
				'placeholder' => 'Enter the class of vessel',
				'order' => 0),
			array(
				'form_key' => 'specs',
				'section_id' => 7,
				'type' => 'text',
				'html_name' => 'role',
				'html_id' => 'role',
				'html_rows' => 0,
				'label' => 'Role',
				'placeholder' => 'Enter the role of the vessel',
				'order' => 1),
			array(
				'form_key' => 'specs',
				'section_id' => 7,
				'type' => 'text',
				'html_name' => 'duration',
				'html_id' => 'duration',
				'html_rows' => 0,
				'label' => 'Duration',
				'placeholder' => 'Enter the duration of the vessel',
				'order' => 2),
			array(
				'form_key' => 'specs',
				'section_id' => 7,
				'type' => 'text',
				'html_name' => 'refit',
				'html_id' => 'refit',
				'html_rows' => 0,
				'label' => 'Time Between Refits',
				'placeholder' => 'Enter the time between refits for this vessel',
				'order' => 3),
			array(
				'form_key' => 'specs',
				'section_id' => 7,
				'type' => 'text',
				'html_name' => 'resupply',
				'html_id' => 'resupply',
				'html_rows' => 0,
				'label' => 'Time Between Resupply',
				'placeholder' => 'Enter the time between resupply of this vessel',
				'order' => 0),
			array(
				'form_key' => 'specs',
				'section_id' => 8,
				'type' => 'text',
				'html_name' => 'length',
				'html_id' => 'length',
				'html_rows' => 0,
				'label' => 'Length',
				'placeholder' => 'e.g. 415 meters',
				'order' => 0),
			array(
				'form_key' => 'specs',
				'section_id' => 8,
				'type' => 'text',
				'html_name' => 'width',
				'html_id' => 'width',
				'html_rows' => 0,
				'label' => 'Width',
				'placeholder' => 'e.g. 75 meters',
				'order' => 1),
			array(
				'form_key' => 'specs',
				'section_id' => 8,
				'type' => 'text',
				'html_name' => 'height',
				'html_id' => 'height',
				'html_rows' => 0,
				'label' => 'Height',
				'placeholder' => 'e.g. 45 meters',
				'order' => 2),
			array(
				'form_key' => 'specs',
				'section_id' => 8,
				'type' => 'text',
				'html_name' => 'decks',
				'html_id' => 'decks',
				'html_rows' => 0,
				'html_class' => 'medium',
				'label' => 'Decks',
				'placeholder' => 'e.g. 10',
				'order' => 3),
			array(
				'form_key' => 'specs',
				'section_id' => 9,
				'type' => 'text',
				'html_name' => 'compliment_officers',
				'html_id' => 'compliment_officers',
				'html_rows' => 0,
				'html_class' => 'medium',
				'label' => 'Officers',
				'placeholder' => 'e.g. 60',
				'order' => 0),
			array(
				'form_key' => 'specs',
				'section_id' => 9,
				'type' => 'text',
				'html_name' => 'compliment_enlisted',
				'html_id' => 'compliment_enlisted',
				'html_rows' => 0,
				'html_class' => 'medium',
				'label' => 'Enlisted Crew',
				'placeholder' => 'e.g. 500',
				'order' => 1),
			array(
				'form_key' => 'specs',
				'section_id' => 9,
				'type' => 'text',
				'html_name' => 'compliment_marines',
				'html_id' => 'compliment_marines',
				'html_rows' => 0,
				'html_class' => 'medium',
				'label' => 'Marines',
				'placeholder' => 'e.g. 48',
				'order' => 2),
			array(
				'form_key' => 'specs',
				'section_id' => 9,
				'type' => 'text',
				'html_name' => 'compliment_civilians',
				'html_id' => 'compliment_civilians',
				'html_rows' => 0,
				'html_class' => 'medium',
				'label' => 'Civilians',
				'placeholder' => 'e.g. 200',
				'order' => 3),
			array(
				'form_key' => 'specs',
				'section_id' => 9,
				'type' => 'text',
				'html_name' => 'compliment_emergency',
				'html_id' => 'compliment_emergency',
				'html_rows' => 0,
				'html_class' => 'medium',
				'label' => 'Emergency Capacity',
				'placeholder' => 'e.g. 2000',
				'order' => 4),
			array(
				'form_key' => 'specs',
				'section_id' => 10,
				'type' => 'text',
				'html_name' => 'speed_normal',
				'html_id' => 'speed_normal',
				'html_rows' => 0,
				'html_class' => 'medium',
				'label' => 'Cruise Speed',
				'placeholder' => 'e.g. Warp 6',
				'order' => 0),
			array(
				'form_key' => 'specs',
				'section_id' => 10,
				'type' => 'text',
				'html_name' => 'speed_max',
				'html_id' => 'speed_max',
				'html_rows' => 0,
				'html_class' => 'medium',
				'label' => 'Maximum Speed',
				'placeholder' => 'e.g. Warp 9',
				'order' => 1),
			array(
				'form_key' => 'specs',
				'section_id' => 10,
				'type' => 'text',
				'html_name' => 'speed_emergency',
				'html_id' => 'speed_emergency',
				'html_rows' => 0,
				'html_class' => 'medium',
				'label' => 'Emergency Speed',
				'placeholder' => 'e.g. Warp 9.9975',
				'order' => 2),
			array(
				'form_key' => 'specs',
				'section_id' => 11,
				'type' => 'textarea',
				'html_name' => 'defensive',
				'html_id' => 'defensive',
				'html_rows' => 5,
				'label' => 'Shields',
				'placeholder' => 'e.g. Enter your vessel\'s defensive systems here',
				'order' => 0),
			array(
				'form_key' => 'specs',
				'section_id' => 11,
				'type' => 'textarea',
				'html_name' => 'weapons',
				'html_id' => 'weapons',
				'html_rows' => 5,
				'label' => 'Weapon Systems',
				'placeholder' => 'e.g. Enter your vessel\'s weapon systems here',
				'order' => 1),
			array(
				'form_key' => 'specs',
				'section_id' => 11,
				'type' => 'textarea',
				'html_name' => 'armament',
				'html_id' => 'armament',
				'html_rows' => 5,
				'label' => 'Armament',
				'placeholder' => 'e.g. Enter your vessel\'s armament here',
				'order' => 2),
			array(
				'form_key' => 'specs',
				'section_id' => 12,
				'type' => 'text',
				'html_name' => 'shuttlebays',
				'html_id' => 'shuttlebays',
				'html_rows' => 0,
				'html_class' => 'small',
				'label' => 'Shuttlebays',
				'order' => 0),
			array(
				'form_key' => 'specs',
				'section_id' => 12,
				'type' => 'textarea',
				'html_name' => 'shuttles',
				'html_id' => 'shuttles',
				'html_rows' => 5,
				'label' => 'Shuttles',
				'placeholder' => 'Enter your vessel\'s shuttles here',
				'order' => 1),
			array(
				'form_key' => 'specs',
				'section_id' => 12,
				'type' => 'textarea',
				'html_name' => 'fighters',
				'html_id' => 'fighters',
				'html_rows' => 5,
				'label' => 'Fighters',
				'placeholder' => 'Enter your vessel\'s fighters here',
				'order' => 2),
			array(
				'form_key' => 'specs',
				'section_id' => 12,
				'type' => 'textarea',
				'html_name' => 'runabouts',
				'html_id' => 'runabouts',
				'html_rows' => 5,
				'label' => 'Runabouts',
				'placeholder' => 'Enter your vessel\'s runabouts here',
				'order' => 3),
			array(
				'form_key' => 'tour',
				'type' => 'text',
				'html_name' => 'location',
				'html_id' => 'location',
				'html_rows' => 0,
				'label' => 'Location',
				'placeholder' => 'Enter the tour item\'s location here',
				'order' => 0),
			array(
				'form_key' => 'tour',
				'type' => 'textarea',
				'html_name' => 'long_desc',
				'html_id' => 'long_desc',
				'html_rows' => 5,
				'label' => 'Description',
				'placeholder' => 'Enter the tour item\'s description here',
				'order' => 1),
			array(
				'form_key' => 'user',
				'type' => 'text',
				'html_name' => 'location',
				'html_id' => 'location',
				'html_rows' => 0,
				'label' => 'Location',
				'placeholder' => 'Enter your location here',
				'order' => 0),
			array(
				'form_key' => 'user',
				'type' => 'textarea',
				'html_name' => 'interests',
				'html_id' => 'interests',
				'html_rows' => 5,
				'label' => 'Interests',
				'placeholder' => 'Enter your interests here',
				'order' => 1),
			array(
				'form_key' => 'user',
				'type' => 'textarea',
				'html_name' => 'bio',
				'html_id' => 'bio',
				'html_rows' => 5,
				'label' => 'Bio',
				'placeholder' => 'Enter your bio information here',
				'order' => 2),
		);

		foreach ($data as $value)
		{
			\DB::insert('form_fields')->set($value)->execute();
		}
	}

	public function down()
	{
		\DBUtil::drop_table('form_fields');
	}
}