ALTER TABLE `nova_access_pages` MODIFY `page_desc` TEXT NULL;
ALTER TABLE `nova_access_roles` MODIFY `role_access` TEXT NULL, MODIFY `role_desc` TEXT NULL;
ALTER TABLE `nova_applications` MODIFY `app_character_name` TEXT NULL, MODIFY `app_message` TEXT NULL;
ALTER TABLE `nova_awards` MODIFY `award_desc` TEXT NULL;
ALTER TABLE `nova_awards_queue` MODIFY `queue_reason` TEXT NULL;
ALTER TABLE `nova_awards_received` MODIFY `awardrec_reason` TEXT NULL;
ALTER TABLE `nova_bans` MODIFY `ban_reason` TEXT NULL;
ALTER TABLE `nova_catalogue_ranks` MODIFY `rankcat_credits` TEXT NULL, MODIFY `rankcat_url` TEXT NULL;
ALTER TABLE `nova_catalogue_skins` MODIFY `skin_credits` TEXT NULL;
ALTER TABLE `nova_characters` MODIFY `user` INT(8) NULL, MODIFY `date_activate` BIGINT(20) NULL, MODIFY `date_deactivate` BIGINT(20) NULL, MODIFY `images` TEXT NULL, MODIFY `rank` INT(10) NULL, MODIFY `position_2` INT(10) NULL, MODIFY `last_post` BIGINT(20) NULL;
ALTER TABLE `nova_characters_data` MODIFY `data_user` INT(8) NULL, MODIFY `data_value` TEXT NULL;
ALTER TABLE `nova_characters_fields` MODIFY `field_type` ENUM('text','select','textarea') NULL DEFAULT 'text', MODIFY `field_class` TEXT NULL, MODIFY `field_label_page` TEXT NULL, MODIFY `field_value` TEXT NULL, MODIFY `field_help` TEXT NULL;
ALTER TABLE `nova_characters_promotions` MODIFY `prom_user` INT(8) NULL;
ALTER TABLE `nova_characters_values` MODIFY `value_content` TEXT NULL;
ALTER TABLE `nova_departments` MODIFY `dept_desc` TEXT NULL;
ALTER TABLE `nova_docking` MODIFY `docking_sim_url` TEXT NULL;
ALTER TABLE `nova_docking_data` MODIFY `data_value` TEXT NULL;
ALTER TABLE `nova_docking_fields` MODIFY `field_type` ENUM('text','select','textarea') NULL DEFAULT 'text', MODIFY `field_class` TEXT NULL, MODIFY `field_label_page` TEXT NULL, MODIFY `field_value` TEXT NULL, MODIFY `field_help` TEXT NULL;
ALTER TABLE `nova_docking_values` MODIFY `value_content` TEXT NULL;
ALTER TABLE `nova_manifests` MODIFY `manifest_desc` TEXT NULL, MODIFY `manifest_header_content` TEXT NULL, MODIFY `manifest_view` TEXT NULL, MODIFY `manifest_metadata` TEXT NULL;
ALTER TABLE `nova_menu_items` MODIFY `menu_link` TEXT NULL;
ALTER TABLE `nova_messages` MODIFY `message_content` TEXT NULL;
ALTER TABLE `nova_mission_groups` MODIFY `misgroup_desc` TEXT NULL;
ALTER TABLE `nova_missions` MODIFY `mission_images` TEXT NULL, MODIFY `mission_group` INT(5) NULL, MODIFY `mission_start` BIGINT(20) NULL, MODIFY `mission_end` BIGINT(20) NULL, MODIFY `mission_desc` TEXT NULL, MODIFY `mission_summary` TEXT NULL, MODIFY `mission_notes` TEXT NULL, MODIFY `mission_notes_updated` BIGINT(20) NULL;
ALTER TABLE `nova_news` MODIFY `news_content` TEXT NULL, MODIFY `news_tags` TEXT NULL;
ALTER TABLE `nova_news_comments` MODIFY `ncomment_content` TEXT NULL;
ALTER TABLE `nova_personallogs` MODIFY `log_content` TEXT NULL, MODIFY `log_tags` TEXT NULL;
ALTER TABLE `nova_personallogs_comments` MODIFY `lcomment_content` TEXT NULL;
ALTER TABLE `nova_positions` MODIFY `pos_desc` TEXT NULL;
ALTER TABLE `nova_posts` MODIFY `post_authors` TEXT NULL, MODIFY `post_authors_users` TEXT NULL, MODIFY `post_saved` INT(8) NULL, MODIFY `post_content` TEXT NULL, MODIFY `post_tags` TEXT NULL, MODIFY `post_participants` TEXT NULL, MODIFY `post_lock_user` INT(8) NULL, MODIFY `post_lock_date` BIGINT(20) NULL;
ALTER TABLE `nova_posts_comments` MODIFY `pcomment_content` TEXT NULL;
ALTER TABLE `nova_privmsgs` MODIFY `privmsgs_content` TEXT NULL;
ALTER TABLE `nova_security_questions` MODIFY `question_value` TEXT NULL;
ALTER TABLE `nova_settings` MODIFY `setting_value` TEXT NULL;
ALTER TABLE `nova_specs` MODIFY `specs_images` TEXT NULL, MODIFY `specs_summary` TEXT NULL;
ALTER TABLE `nova_specs_data` MODIFY `data_value` TEXT NULL, MODIFY `data_updated` BIGINT(20) NULL;
ALTER TABLE `nova_specs_fields` MODIFY `field_type` ENUM('text','select','textarea') NULL DEFAULT 'text', MODIFY `field_class` TEXT NULL, MODIFY `field_label_page` TEXT NULL, MODIFY `field_value` TEXT NULL, MODIFY `field_help` TEXT NULL;
ALTER TABLE `nova_specs_values` MODIFY `value_content` TEXT NULL;
ALTER TABLE `nova_system_info` MODIFY `sys_last_update` BIGINT(20) NULL;
ALTER TABLE `nova_tour` MODIFY `tour_images` TEXT NULL, MODIFY `tour_summary` TEXT NULL;
ALTER TABLE `nova_tour_data` MODIFY `data_value` TEXT NULL, MODIFY `data_updated` BIGINT(20) NULL;
ALTER TABLE `nova_tour_fields` MODIFY `field_type` ENUM('text','select','textarea') NULL DEFAULT 'text', MODIFY `field_class` TEXT NULL, MODIFY `field_label_page` TEXT NULL, MODIFY `field_value` TEXT NULL, MODIFY `field_help` TEXT NULL;
ALTER TABLE `nova_tour_values` MODIFY `value_content` TEXT NULL;
ALTER TABLE `nova_tour_decks` MODIFY `deck_content` TEXT NULL;
ALTER TABLE `nova_uploads` MODIFY `upload_filename` TEXT NULL;
ALTER TABLE `nova_user_loa` MODIFY `loa_start_date` BIGINT(20) NULL, MODIFY `loa_end_date` BIGINT(20) NULL, MODIFY `loa_duration` TEXT NULL, MODIFY `loa_reason` TEXT NULL;
ALTER TABLE `nova_user_prefs` MODIFY `pref_default` TEXT NULL;
ALTER TABLE `nova_user_prefs_values` MODIFY `prefvalue_value` TEXT NULL;
ALTER TABLE `nova_users` MODIFY `instant_message` TEXT NULL, MODIFY `main_char` INT(8) NULL, MODIFY `access_role` INT(5) NULL, MODIFY `join_date` BIGINT(20) NULL, MODIFY `leave_date` BIGINT(20) NULL, MODIFY `last_post` BIGINT(20) NULL, MODIFY `last_login` BIGINT(20) NULL, MODIFY `location` TEXT NULL, MODIFY `interests` TEXT NULL, MODIFY `bio` TEXT NULL, MODIFY `my_links` TEXT NULL, MODIFY `last_update` BIGINT(20) NULL;
ALTER TABLE `nova_wiki_categories` MODIFY `wikicat_desc` TEXT NULL;
ALTER TABLE `nova_wiki_comments` MODIFY `wcomment_content` TEXT NULL;
ALTER TABLE `nova_wiki_drafts` MODIFY `draft_id_old` INT(10) NULL, MODIFY `draft_summary` TEXT NULL, MODIFY `draft_content` TEXT NULL, MODIFY `draft_categories` TEXT NULL, MODIFY `draft_changed_comments` TEXT NULL;
ALTER TABLE `nova_wiki_pages` MODIFY `page_updated_at` BIGINT(20) NULL, MODIFY `page_updated_by_user` INT(8) NULL, MODIFY `page_updated_by_character` INT(8) NULL;
ALTER TABLE `nova_wiki_restrictions` MODIFY `restr_updated_at` BIGINT(20) NULL, MODIFY `restr_updated_by` INT(8) NULL, MODIFY `restrictions` TEXT NULL;