<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
/**
 * Update Versions
 *
 * This file contains all the version of the system that can be udpated.
 * Do not edit this file. Doing so can break the Nova update system in
 * the event your server doesn't support dynamically pulling the update
 * directory's file listing.
 */

$version_array = array(
	'100', '101', '102', '103', '104', '105', '106',
	'110', '111', '112',
	'120', '121', '122', '123', '124', '125', '126',
	'200', '201', '202', '203',
	'210', '211', '212',
);
