<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
/*
|---------------------------------------------------------------
| UPDATE VERSIONS
|---------------------------------------------------------------
|
| File: assets/update/versions.php
| System Version: 1.2.3
|
| File containing all the versions the system can updated from
|
| DO NOT EDIT THIS FILE. DOING SO WILL BREAK THE NOVA UPDATE SYSTEM
|
*/

$version_array = array(
	'100', '101', '102', '103', '104', '105', '106', '110', '111', '112', '120', '121', '122'
);

/* End of file versions.php */
/* Location: application/assets/update/versions.php */